//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Qualification
    {
        public int ID { get; set; }
        public string Qname { get; set; }
        public int EmpID { get; set; }
        public string Qcertificate { get; set; }
    }
}
